#!/bin/bash

echo "===Launching MAPIS==="

cd ~/Workspace/api.feunyx-bids
php artisan start &
echo "=> bids"

cd ~/Workspace/api.feunyx-accounts
php artisan start &
echo "=> accounts"

cd ~/Workspace/api.feunyx-shared
php artisan start &
echo "=> shared"

cd ~/Workspace/api.feunyx-mails
php artisan start &
echo "=> mails"

cd ~/Workspace/api.feunyx-ttcompanies
php artisan start &
echo "=> ttcompanies"

cd ~/Workspace/api.feunyx-notifications
php artisan start &
echo "=> notification"

cd ~/Workspace/api.feunyx-contactor
php artisan start &
echo "=> contactor"

cd ~/Workspace/api.feunyx-groups
php artisan start &
echo "=> groups"

echo "===Done==="
