# Generated by Django 3.0.7 on 2020-08-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('Firstname', models.TextField(null=True)),
                ('Phone', models.TextField(null=True)),
                ('Smartphone', models.TextField()),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Street_number', models.TextField(null=True)),
                ('Street', models.TextField(null=True)),
                ('Postal_code', models.TextField(null=True)),
                ('City', models.TextField(null=True)),
                ('Street_number_site', models.TextField(null=True)),
                ('Street_site', models.TextField(null=True)),
                ('Postal_code_site', models.TextField(null=True)),
                ('City_site', models.TextField(null=True)),
                ('Stamp', models.ImageField(null=True, upload_to='')),
                ('Date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Couleur_Bar_Seuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Contremarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Habillage_Limon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Limon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Parquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Parquet_Dalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marches', models.IntegerField(null=True)),
                ('decor_marches', models.TextField(null=True)),
                ('nombre_contremarches', models.IntegerField(null=True)),
                ('decor_contremarches', models.TextField(null=True)),
                ('nombre_profile_alu', models.IntegerField(null=True)),
                ('type_profile_alu', models.TextField(null=True)),
                ('nombre_plinthes', models.IntegerField(null=True)),
                ('taille_plinthes', models.TextField(null=True)),
                ('nombre_barres_seuil', models.IntegerField(null=True)),
                ('type_barres_seuil', models.TextField(null=True)),
                ('couleur_barres_seuil', models.TextField(null=True)),
                ('nombre_marches_paliere', models.IntegerField(null=True)),
                ('type_marches_paliere', models.TextField(null=True)),
                ('taille_marches_paliere', models.TextField(null=True)),
                ('marche_Eclairee', models.IntegerField(null=True)),
                ('marche_Non_Eclairee', models.IntegerField(null=True)),
                ('interrupteur', models.IntegerField(null=True)),
                ('detecteur', models.IntegerField(null=True)),
                ('unite_commande', models.IntegerField(null=True)),
                ('transfo_35w', models.IntegerField(null=True)),
                ('transfo_75w', models.IntegerField(null=True)),
                ('transfo_100w', models.IntegerField(null=True)),
                ('stratifie_rouleau', models.TextField(null=True)),
                ('profile_limon_l18', models.IntegerField(null=True)),
                ('profile_limon_l28', models.IntegerField(null=True)),
                ('profile_limon_l80', models.IntegerField(null=True)),
                ('profile_limon_l120', models.IntegerField(null=True)),
                ('profile_limon_u58', models.IntegerField(null=True)),
                ('profile_limon_u65', models.IntegerField(null=True)),
                ('profile_limon_u75', models.IntegerField(null=True)),
                ('profile_limon_u85', models.IntegerField(null=True)),
                ('metrage_parquet', models.TextField(null=True)),
                ('metrage_parquet_dalle', models.TextField(null=True)),
                ('decor_parquet_dalle', models.TextField(null=True)),
                ('profile_40mm', models.IntegerField(null=True)),
                ('profile_58mm', models.IntegerField(null=True)),
                ('droit_58mm', models.IntegerField(null=True)),
                ('droit_80mm', models.IntegerField(null=True)),
                ('droit_blanc_80mm', models.IntegerField(null=True)),
                ('angles_exterieurs', models.IntegerField(null=True)),
                ('angles_interieurs', models.IntegerField(null=True)),
                ('nombre_module_fin', models.IntegerField(null=True)),
                ('rouleau', models.IntegerField(null=True)),
                ('rouleau_etange', models.IntegerField(null=True)),
                ('panneau', models.IntegerField(null=True)),
                ('commentaire', models.TextField(null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='Tailles_Marche_Paliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tailles_Panneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tailles_Plinthes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Bar_Seuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Marche_Paliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poses_Parquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Panneaux_Palier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('taille', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Mesure_Marches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stair', models.TextField(null=True)),
                ('Diagonal', models.TextField(null=True)),
                ('DepthL', models.TextField(null=True)),
                ('DepthR', models.TextField(null=True)),
                ('RetourG', models.BooleanField(default=False, null=True)),
                ('RetourD', models.BooleanField(default=False, null=True)),
                ('PlintheG', models.BooleanField(default=False, null=True)),
                ('PlintheD', models.BooleanField(default=False, null=True)),
                ('ProfileArriere', models.BooleanField(default=False, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Marches_Ronde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('taille', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Limons_Interieur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.TextField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('orientation', models.BooleanField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Limons_Exterieur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Habillages_Limon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('decor', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Habillages_Dessus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Deposes_Ancien_Revetement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Decoupes_Nez_Marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Creations_Contremarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Balustrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
    ]
