# Generated by Django 3.0.7 on 2020-06-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur_Bar_Seuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Contremarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Limon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decors_Parquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marche_Eclairee', models.IntegerField(null=True)),
                ('marche_Non_Eclairee', models.IntegerField(null=True)),
                ('interrupteur', models.IntegerField(null=True)),
                ('detecteur', models.IntegerField(null=True)),
                ('unite_commande', models.IntegerField(null=True)),
                ('transfo_35w', models.IntegerField(null=True)),
                ('transfo_75w', models.IntegerField(null=True)),
                ('transfo_100w', models.IntegerField(null=True)),
                ('profile_arriere', models.BooleanField(null=True)),
                ('stratifie_rouleau', models.BooleanField(null=True)),
                ('profile_limon_l18', models.IntegerField(null=True)),
                ('profile_limon_l28', models.IntegerField(null=True)),
                ('profile_limon_l80', models.IntegerField(null=True)),
                ('profile_limon_l120', models.IntegerField(null=True)),
                ('profile_limon_u58', models.IntegerField(null=True)),
                ('profile_limon_u65', models.IntegerField(null=True)),
                ('profile_limon_u75', models.IntegerField(null=True)),
                ('profile_limon_u85', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tailles_Marche_Paliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tailles_Panneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tailles_Plinthes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Bar_Seuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Marche_Paliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('typeProfile', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='PosesParquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='PlinthesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_40mm', models.IntegerField(null=True)),
                ('profile_58mm', models.IntegerField(null=True)),
                ('droit_58mm', models.IntegerField(null=True)),
                ('droit_80mm', models.IntegerField(null=True)),
                ('droit_blanc_80mm', models.IntegerField(null=True)),
                ('angles_exterieurs', models.IntegerField(null=True)),
                ('angles_interieurs', models.IntegerField(null=True)),
                ('nombre_module_fin', models.IntegerField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Plinthes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('typeProfile', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Parquets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrage', models.TextField(null=True)),
                ('dalle_decor', models.TextField(null=True)),
                ('dalle_metrage', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='PanneauxPalier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('taille', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='MesureMarches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stair', models.TextField(null=True)),
                ('Diagonal', models.TextField(null=True)),
                ('DepthL', models.TextField(null=True)),
                ('DepthR', models.TextField(null=True)),
                ('RetourG', models.BooleanField(null=True)),
                ('RetourD', models.BooleanField(null=True)),
                ('PlintheG', models.BooleanField(null=True)),
                ('PlintheD', models.BooleanField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='MarchesRonde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('taille', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='MarchesPaliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('typeMarchePaliere', models.TextField(null=True)),
                ('decor', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Marches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('decor', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='LimonsInterieur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('orientation', models.BooleanField()),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='LimonsExterieur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Isolations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rouleau', models.IntegerField(null=True)),
                ('rouleau_etange', models.IntegerField(null=True)),
                ('panneau', models.IntegerField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='HabillagesLimon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('decor', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='HabillagesDessus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='DeposesAncienRevetement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='DecoupesNezMarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='CreationsContremarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Contremarches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('decor', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('Firstname', models.TextField(null=True)),
                ('Phone', models.TextField(null=True)),
                ('Smartphone', models.TextField()),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Street_number', models.TextField(null=True)),
                ('Street', models.TextField(null=True)),
                ('Postal_code', models.TextField(null=True)),
                ('City', models.TextField(null=True)),
                ('Stamp', models.ImageField(null=True, upload_to='')),
                ('Date_created', models.DateField(auto_now=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='BarresSeuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('taille', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Balustrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('pdl', models.TextField(null=True)),
                ('devis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriseMesure.Devis')),
            ],
        ),
    ]
