# Generated by Django 3.0.7 on 2020-06-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriseMesure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarresSeuil',
            new_name='Barres_Seuil',
        ),
        migrations.RenameModel(
            old_name='CreationsContremarche',
            new_name='Creations_Contremarche',
        ),
        migrations.RenameModel(
            old_name='DecoupesNezMarche',
            new_name='Decoupes_Nez_Marche',
        ),
        migrations.RenameModel(
            old_name='DeposesAncienRevetement',
            new_name='Deposes_Ancien_Revetement',
        ),
        migrations.RenameModel(
            old_name='HabillagesDessus',
            new_name='Habillages_Dessus',
        ),
        migrations.RenameModel(
            old_name='HabillagesLimon',
            new_name='Habillages_Limon',
        ),
        migrations.RenameModel(
            old_name='LimonsExterieur',
            new_name='Limons_Exterieur',
        ),
        migrations.RenameModel(
            old_name='LimonsInterieur',
            new_name='Limons_Interieur',
        ),
        migrations.RenameModel(
            old_name='MarchesPaliere',
            new_name='Marches_Paliere',
        ),
        migrations.RenameModel(
            old_name='MarchesRonde',
            new_name='Marches_Ronde',
        ),
        migrations.RenameModel(
            old_name='MesureMarches',
            new_name='Mesure_Marches',
        ),
        migrations.RenameModel(
            old_name='PanneauxPalier',
            new_name='Panneaux_Palier',
        ),
        migrations.RenameModel(
            old_name='PlinthesProfile',
            new_name='Plinthes_Profile',
        ),
        migrations.RenameModel(
            old_name='PosesParquet',
            new_name='Poses_Parquet',
        ),
    ]
